/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_analytics_pipeline_acoustic_training_WarpCTC */

#ifndef _Included_com_intel_analytics_pipeline_acoustic_training_WarpCTC
#define _Included_com_intel_analytics_pipeline_acoustic_training_WarpCTC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_analytics_pipeline_acoustic_training_WarpCTC
 * Method:    computeCTCLoss
 * Signature: ([F[F[I[I[III[FI)I
 */
JNIEXPORT jint JNICALL Java_com_intel_analytics_pipeline_acoustic_training_WarpCTC_computeCTCLoss
  (JNIEnv *, jobject, jfloatArray, jfloatArray, jintArray, jintArray, jintArray, jint, jint, jfloatArray, jint);

/*
 * Class:     com_intel_analytics_pipeline_acoustic_training_WarpCTC
 * Method:    printHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_intel_analytics_pipeline_acoustic_training_WarpCTC_printHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif